### PR TITLE
Make flag render behind hero

### PR DESCRIPTION
**Pull request by jkoppel**
@Kert  Please review

### CODE REVIEW

**Comment by PierceLBrooks** [comment]
I'm unfortunately not seeing the hero at all right now. I repackaged the AGG assets and such, but with no luck. Here is a personal test merge branch:
https://github.com/PierceLBrooks/project-ironfist/commit/c98fe6da7f79f14ccfaefaf93b522ca84847c7b6

**Comment by PierceLBrooks** [comment]
Should ironfist_save::hero_t::relatedToUnknown() be refactored to ironfist_save::hero_t::directionFacing() ?

**Comment by jkoppel** [comment]
Eventually, but it should wait for other schema changes.

Currently, every time we change the save-game schema, it will *break* all existing savegames.

**Comment by jkoppel** [comment]
So, have you reviewed the code and found no other concerns?

**Comment by Kert** [comment]
Are you sure you want this to be done before adding cyborg specific adventure map hero graphics?
Because it requires adding cbrg32.icn (like wzrd32.icn e.t.c.) and they are stored in advManager::heroIcons[6] array.
What I mean is that if we want to add separate graphics we'll need to import the whole advManager::DrawCell and advManager::DrawCursor functions + advManager::Open (this one is easy) and store this data somewhere else.
We can't use the current code in this branch for that since it draws stuff on top of what was drawn by original functions.
I suggest that we implement the feature of rendering flag behind hero along with cyborg heroes and maybe even exactly for them.

**Comment by jkoppel** [comment]
Okay. Very sad.

**Pull request closed without merging**
