### PR TITLE
Hotfixes

### PR DESCRIPTION
**Pull request by Kert**
Fixed possible unitialized variable use
Fixed going into expansion campaign crash if AppData registry entry is not pointing to game's folder

### CODE REVIEW

**Comment by jkoppel** [comment]
On bug 1: Can you explain what was broken and what your change does?
On bug 2: What happens if you run the game from a different folder? (E.g.: In the command line, from a different directory, do something like "..\HoMM2\ironfist.exe".)

**Comment by Kert** [comment]
> On bug 1: Can you explain what was broken and what your change does?
> On bug 2: What happens if you run the game from a different folder? (E.g.: In the command line, from a different directory, do something like "..\HoMM2\ironfist.exe".)

1. randomHeroIdx is not always initialized when the code gets to those lines
2. Error loading creatures.xml

**Comment by jkoppel** [comment]
1. What's the relation between randomHeroIdx and mapExtraHero->heroID ?
2. You're saying...you get that bug both in the old and new versions?

**Comment by Kert** [comment]
> 1. What's the relation between randomHeroIdx and mapExtraHero->heroID ?
> 2. You're saying...you get that bug both in the old and new versions?
1. mapExtraHero->heroID is the actual portrait to be used
randomHeroIdx is heroes[] index which is most of the time the same as portrait ID, except when portrait ID is >= 54 (NUM_HEROES)
2. Your situation described was never in our code. I think even original game would break if run from another folder through command line. Who would do this anyway?!

**Comment by jkoppel** [comment]
Okay; I was just asking that, as your code is assuming the correct current directory.

I actually was able to run HEROES2W.exe from a different folder, but not Ironfist. There is no additional harm from merging this.

**Pull request merged**
